load:
  type: constant
  stages:
  - rate: 1
    duration: 30
  base_seed: 12345    # Fixed seed for reproducible runs
api:
  type: completion
  streaming: true
server:
  type: vllm
  model_name: meta-llama/Llama-3.3-70B-Instruct
  base_url: http://35.209.55.248:80
  ignore_eos: true
tokenizer:
  pretrained_model_name_or_path: meta-llama/Llama-3.3-70B-Instruct
data:
  # type: shareGPT # blocked by https://github.com/kubernetes-sigs/inference-perf/issues/429
  type: random
  input_distribution:
    min: 2048             # min length of the synthetic prompts
    max: 2048            # max length of the synthetic prompts
    mean: 2048            # mean length of the synthetic prompts
    std_dev: 0         # standard deviation of the length of the synthetic prompts
    total_count: 100    # total number of prompts to generate to fit the above mentioned distribution constraints
  output_distribution:
    min: 10             # min length of the output to be generated
    max: 10            # max length of the output to be generated
    mean: 10            # mean length of the output to be generated
    std_dev: 0         # standard deviation of the length of the output to be generated
    total_count: 100    # total number of output lengths to generate to fit the above mentioned distribution constraints
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: false
  prometheus:
    summary: false
    per_stage: false
