apiVersion: batch/v1
kind: Job
metadata:
  name: inference-perf
  labels:
    app: inference-perf
spec:
  template:
    metadata:
      labels:
        app: inference-perf
    spec:
      containers:
        - name: inference-perf
          image: quay.io/inference-perf/inference-perf:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              inference-perf --config_file /etc/config/config.yml
              echo "Benchmark finished. Sleeping for 15 sec to allow file copy..."
              sleep 15
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
                  optional: true
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: inference-perf-config