export PROJECT_ID=<YOUR_PROJECT_ID>
export CLUSTER=<YOUR_CLUSTER_NAME>
export LOCATION=<YOUR_GCP_REGION>
export ZONE=<YOUR_GCP_ZONE>
export RESERVATION=<YOUR_RESERVATION>
export NETWORK_NAME_1=<YOUR_NETWORK> # Set to "default" to use the default network
export NETWORK_NAME_2=<YOUR_NETWORK> # Set to "default" to use the default network
export SUBNET_NAME_1=<YOUR_SUBNET>
export SUBNET_NAME_2=<YOUR_SUBNET>
export SUBNET_CIDR_RANGE_1=172.16.0.0/26 # ATTN: Make sure the IP range does not overlap with other subnets!!!
export SUBNET_CIDR_RANGE_2=10.10.0.0/18
export FW_RULE_NAME_1=<YOUR_FIREWALL_RULE>
export FW_RULE_NAME_2=<YOUR_FIREWALL_RULE>
export NODE_POOL=v7x-singlehost-pool
export BENCHMARK_NODE_POOL=benchmark
export MACHINE_TYPE=tpu7x-standard-4t
export NAMESPACE=llm-d-pd
export HF_TOKEN=<YOUR_HF_TOKEN>
