export PROJECT_ID=<YOUR_PROJECT_ID>
PREFIX="${USER}-"
SUFFIX="-test"
export CLUSTER=${PREFIX}v7x${SUFFIX}
export LOCATION=us-central1
export ZONE=us-central1-c
export RESERVATION=<YOUR_RESERVATION>
export NETWORK_NAME_1=${PREFIX}net1${SUFFIX} # Set to "default" to use the default network
export NETWORK_NAME_2=${PREFIX}net2${SUFFIX} # Set to "default" to use the default network
export SUBNET_NAME_1=${PREFIX}subnet1${SUFFIX}
export SUBNET_NAME_2=${PREFIX}subnet2${SUFFIX}
export FW_RULE_NAME_1=${PREFIX}firewall-rule1${SUFFIX}
export FW_RULE_NAME_2=${PREFIX}firewall-rule2${SUFFIX}
export SUBNET_CIDR_RANGE_1=172.16.0.0/26 # ATTN: Make sure the IP range does not overlap with other subnets!!!
export SUBNET_CIDR_RANGE_2=10.10.0.0/18
export NODE_POOL=v7x-singlehost-pool
export BENCHMARK_NODE_POOL=benchmark
export MACHINE_TYPE=tpu7x-standard-4t
export NAMESPACE=llm-d-pd
export HF_TOKEN=<YOUR_HF_TOKEN>
export ARTIFACT_REGISTRY_REPO="llm-d-pd-jax-tpu-benchmark"   # Google Artifact Registry repository name
export PD_POD_IMAGE="${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/vllm-tpu-custom-jaxlib:v0.18.0"
