apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../common/podmonitors

patches:
  - path: patch-xpu.yaml
  - target:
      kind: Deployment
      name: ms-pd-llm-d-modelservice-decode
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
      - op: remove
        path: /spec/template/spec/containers/0/resources/requests/nvidia.com~1gpu
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/rdma~1ib
      - op: remove
        path: /spec/template/spec/containers/0/resources/requests/rdma~1ib
  - target:
      kind: Deployment
      name: ms-pd-llm-d-modelservice-prefill
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
      - op: remove
        path: /spec/template/spec/containers/0/resources/requests/nvidia.com~1gpu
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits/rdma~1ib
      - op: remove
        path: /spec/template/spec/containers/0/resources/requests/rdma~1ib
